## Numpy - Python array

In [1]:
import numpy as np

In [2]:
l = range(1000)

In [3]:
array = np.array(l)

In [5]:
array.size

1000

In [6]:
array.itemsize # 4 bytes in numpy array

4

In [7]:
a = np.array([[1,2],[3,4],[5,6]])

In [8]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
a.ndim

2

In [17]:
a = np.array([[1,2],[3,4],[5,6]],dtype = np.float)

In [18]:
a.dtype

dtype('float64')

In [19]:
a.itemsize

8

In [20]:
a.size

6

In [21]:
a.shape

(3, 2)

In [22]:
a = np.array([[1,2],[3,4],[5,6]],dtype = complex)

In [23]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [24]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.arange(3,50,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [33]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
a.reshape(2,3)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [38]:
a.ravel() # make array to one dimension. note :-It return the value output

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [42]:
a = np.array([[1,2],[3,4],[5,6]])

In [43]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
a.min()

1

In [46]:
a.mean()

3.5

In [48]:
a.max()

6

In [49]:
a.sum()

21

In [50]:
np.std(a)

1.707825127659933

In [57]:
b = a 
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
a+b

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [59]:
a*b

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [60]:
a-b

array([[0, 0],
       [0, 0],
       [0, 0]])

In [61]:
a/b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Numpy slice/ index

In [63]:
a[1]

array([3, 4])

In [64]:
a[:4]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
a[1,1]

4

In [69]:
a[0,1]

2

In [70]:
a[2,1]

6

In [71]:
a[-1]

array([5, 6])

In [73]:
a[-1,:]

array([5, 6])

In [91]:
a[:]

array([1, 2, 3, 4, 5, 6])

In [93]:
for i in a:
    print(i)

1
2
3
4
5
6


In [102]:
a =np.arange(6).reshape(3,2)
b =np.arange(6,12).reshape(3,2)
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [103]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [104]:
a = np.arange(30).reshape(2,15)

In [114]:
b = np.arange(25,55).reshape(2,15)
a>4

array([[False, False, False, False, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True]])

In [115]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])